### ISSUE TITLE
Game crash with enchanted shears

### ISSUE THREAD

**Issue by chimericdream** [nicguzzo/deepslateinstamine_fabric#4]
Minecraft: 1.19
Deepslate Instamine: 2.1
Fabric API: 0.58.0
Architectury API: 5.12.45

When using shears enchanted with Efficiency 5 (tested with unenchanted as well as Eff4; only Eff5 crashed), there is a client crash trying to convert `ShearsItem` to `ToolItem`. This only happens when the player also has the Haste II effect as well.

```
java.lang.ClassCastException: class net.minecraft.class_1820 cannot be cast to class net.minecraft.class_1831 (net.minecraft.class_1820 and net.minecraft.class_1831 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @21a947fe)
	at net.nicguzzo.deepslateinstamine.DeepslateInstamineMod.instamine(DeepslateInstamineMod.java:38)
	at net.minecraft.class_1657.handler$zde000$getDestroySpeed(class_1657.java:3850)
	at net.minecraft.class_1657.method_7351(class_1657.java)
	at net.minecraft.class_4970.method_9594(class_4970.java:382)
	at net.minecraft.class_4970$class_4971.method_26165(class_4970.java:820)
	at net.minecraft.class_636.method_41930(class_636.java:180)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2910(class_636.java:175)
	at net.minecraft.class_310.method_1536(class_310.java:1648)
	at net.minecraft.class_310.method_1508(class_310.java:1961)
	at net.minecraft.class_310.method_1574(class_310.java:1791)
	at net.minecraft.class_310.method_1523(class_310.java:1101)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by nicguzzo** [comment]
I'll fix this asap

**Comment by Earthcomputer** [comment]
It's caused by this cast [here](https://github.com/nicguzzo/deepslateinstamine/blob/373254e4920ce1b7309c247deb1de310fbf759c8/fabric/src/main/java/net/nicguzzo/deepslateinstamine/mixin/PlayerMixin.java#L35). You should not be modifying the mining speed if the item is not a `TieredItem`.

**Comment by nicguzzo** [comment]
fixed
